### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by c-w** [mehanix/arcada#8]
Hi there :wave: could you clarify the license terms under which this project is published? I couldn't find anything in the usual locations (`package.json` or `LICENSE.md`). Thanks in advance!

**Comment by mehanix** [comment]
Hi, sorry I missed this and thanks for asking. I've added it just now. If you use this for some derivative work, I would be really happy if you provide credit & send it my way, I would be really happy to see it :) 

I'm also adding it to the backend (https://github.com/mehanix/arcada-backend). 

Someone made a docker image with the app, maybe that could be useful to you as well! https://github.com/perguth/arcada-setup

**Comment by c-w** [comment]
Thank you 🙏
